#include "NativeCompiler.hpp"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#ifdef _WIN32
#  include <process.h>
#  define VAYU_GETPID() _getpid()
#else
#  include <unistd.h>
#  define VAYU_GETPID() getpid()
#endif

namespace vayu {

    // ===========================================================================
    // Constructor — picks sensible default tool paths per platform
    // ===========================================================================

    NativeCompiler::NativeCompiler() {
#ifdef _WIN32
        qbePath_ = "tools\\qbe.exe";
        ccPath_ = "gcc";
        qbeTarget_ = "amd64_win";
#else
        qbePath_ = "tools/qbe";
        ccPath_ = "cc";
        qbeTarget_ = "amd64_sysv";
#endif

        if (const char* p = std::getenv("VAYU_QBE"))        qbePath_ = p;
        if (const char* p = std::getenv("VAYU_CC"))         ccPath_ = p;
        if (const char* p = std::getenv("VAYU_QBE_TARGET")) qbeTarget_ = p;
    }

    // ===========================================================================
    // AST analysis helpers
    // ===========================================================================

    static bool isBoolExpr(const Expr* e) {
        if (!e) return false;
        switch (e->kind) {
        case ExprKind::BoolLit:
            return true;
        case ExprKind::Unary: {
            auto* u = static_cast<const UnaryExpr*>(e);
            return u->op == UnOp::Not;
        }
        case ExprKind::Binary: {
            auto* b = static_cast<const BinaryExpr*>(e);
            switch (b->op) {
            case BinOp::Eq: case BinOp::NotEq:
            case BinOp::Lt: case BinOp::Gt:
            case BinOp::LtEq: case BinOp::GtEq:
            case BinOp::And: case BinOp::Or:
            case BinOp::In: case BinOp::Is:
                return true;
            default:
                return false;
            }
        }
        default:
            return false;
        }
    }

    static void collectVarsStmt(const Stmt* s, std::unordered_set<std::string>& out);
    static void collectVarsBlock(const Block& b, std::unordered_set<std::string>& out);

    static void collectVarsStmt(const Stmt* s, std::unordered_set<std::string>& out) {
        if (!s) return;
        switch (s->kind) {
        case StmtKind::Assign: {
            auto* n = static_cast<const AssignStmt*>(s);
            if (n->target->kind == ExprKind::NameRef)
                out.insert(static_cast<const NameRefExpr*>(n->target.get())->name);
            break;
        }
        case StmtKind::AnnotAssign: {
            auto* n = static_cast<const AnnotAssignStmt*>(s);
            out.insert(n->name);
            break;
        }
        case StmtKind::If: {
            auto* n = static_cast<const IfStmt*>(s);
            collectVarsBlock(n->thenBody, out);
            for (auto& ec : n->elifs) collectVarsBlock(ec.body, out);
            if (n->elseBody) collectVarsBlock(*n->elseBody, out);
            break;
        }
        case StmtKind::While: {
            auto* n = static_cast<const WhileStmt*>(s);
            collectVarsBlock(n->body, out);
            break;
        }
        default: break;
        }
    }

    static void collectVarsBlock(const Block& b, std::unordered_set<std::string>& out) {
        for (auto& s : b.stmts) collectVarsStmt(s.get(), out);
    }

    // ===========================================================================
    // QBE IL emitter
    // ===========================================================================

    namespace {

        class QbeEmitter {
        public:
            std::string emit(const Block& program) {
                std::unordered_set<std::string> names;
                collectVarsBlock(program, names);

                raw("# Generated by Vayu (QBE backend)");
                raw("");
                raw("export function $vayu_main() {");
                raw("@start");

                for (auto& n : names) {
                    std::string slot = "%" + mangle(n) + "_slot";
                    varSlot_[n] = slot;
                    line(slot + " =l alloc8 8");
                    line("storel 0, " + slot);
                }

                emitBlock(program);
                line("ret");
                raw("}");

                return out_;
            }

        private:
            std::string out_;
            int nextTemp_ = 0;
            int nextLabel_ = 0;
            std::unordered_map<std::string, std::string> varSlot_;

            std::string newTemp() { return "%t" + std::to_string(nextTemp_++); }
            std::string newLabel(const char* prefix) {
                return "@" + std::string(prefix) + std::to_string(nextLabel_++);
            }
            void line(const std::string& s) { out_ += "    " + s + "\n"; }
            void raw(const std::string& s) { out_ += s + "\n"; }

            static std::string mangle(const std::string& s) {
                std::string r = "v";
                for (char c : s) {
                    if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                        (c >= '0' && c <= '9') || c == '_')
                        r += c;
                    else
                        r += '_';
                }
                return r;
            }

            std::string lookupSlot(const std::string& name) {
                auto it = varSlot_.find(name);
                if (it == varSlot_.end()) return {};
                return it->second;
            }

            std::string emitExpr(const Expr* e) {
                if (!e) return "0";

                switch (e->kind) {
                case ExprKind::IntLit: {
                    auto* n = static_cast<const IntLitExpr*>(e);
                    return std::to_string(n->value);
                }
                case ExprKind::BoolLit: {
                    auto* n = static_cast<const BoolLitExpr*>(e);
                    return n->value ? "1" : "0";
                }
                case ExprKind::NoneLit:
                    return "0";

                case ExprKind::NameRef: {
                    auto* n = static_cast<const NameRefExpr*>(e);
                    std::string slot = lookupSlot(n->name);
                    if (slot.empty())
                        throw std::runtime_error(
                            "native: variable '" + n->name + "' not declared");
                    std::string t = newTemp();
                    line(t + " =l loadl " + slot);
                    return t;
                }

                case ExprKind::Grouping:
                    return emitExpr(static_cast<const GroupingExpr*>(e)->inner.get());

                case ExprKind::Unary: {
                    auto* n = static_cast<const UnaryExpr*>(e);
                    std::string v = emitExpr(n->operand.get());
                    switch (n->op) {
                    case UnOp::Pos:
                        return v;
                    case UnOp::Neg: {
                        std::string t = newTemp();
                        line(t + " =l sub 0, " + v);
                        return t;
                    }
                    case UnOp::Not: {
                        std::string c = newTemp();
                        line(c + " =w ceql " + v + ", 0");
                        std::string ext = newTemp();
                        line(ext + " =l extsw " + c);
                        return ext;
                    }
                    }
                    return v;
                }

                case ExprKind::Binary: {
                    auto* n = static_cast<const BinaryExpr*>(e);

                    if (n->op == BinOp::And || n->op == BinOp::Or) {
                        std::string a = emitExpr(n->lhs.get());
                        std::string b = emitExpr(n->rhs.get());
                        std::string ab = newTemp();
                        line(ab + " =w cnel " + a + ", 0");
                        std::string bb = newTemp();
                        line(bb + " =w cnel " + b + ", 0");
                        std::string r = newTemp();
                        line(r + " =w " + (n->op == BinOp::And ? "and" : "or") +
                            " " + ab + ", " + bb);
                        std::string ext = newTemp();
                        line(ext + " =l extsw " + r);
                        return ext;
                    }

                    std::string a = emitExpr(n->lhs.get());
                    std::string b = emitExpr(n->rhs.get());

                    switch (n->op) {
                    case BinOp::Add: {
                        std::string t = newTemp();
                        line(t + " =l add " + a + ", " + b);
                        return t;
                    }
                    case BinOp::Sub: {
                        std::string t = newTemp();
                        line(t + " =l sub " + a + ", " + b);
                        return t;
                    }
                    case BinOp::Mul: {
                        std::string t = newTemp();
                        line(t + " =l mul " + a + ", " + b);
                        return t;
                    }
                    case BinOp::Div: {
                        std::string t = newTemp();
                        line(t + " =l div " + a + ", " + b);
                        return t;
                    }
                    case BinOp::FloorDiv: {
                        std::string t = newTemp();
                        line(t + " =l call $vayu_floordiv(l " + a + ", l " + b + ")");
                        return t;
                    }
                    case BinOp::Mod: {
                        std::string t = newTemp();
                        line(t + " =l call $vayu_mod(l " + a + ", l " + b + ")");
                        return t;
                    }

                    case BinOp::Eq:
                    case BinOp::NotEq:
                    case BinOp::Lt:
                    case BinOp::Gt:
                    case BinOp::LtEq:
                    case BinOp::GtEq: {
                        const char* opName = nullptr;
                        switch (n->op) {
                        case BinOp::Eq:    opName = "ceql";  break;
                        case BinOp::NotEq: opName = "cnel";  break;
                        case BinOp::Lt:    opName = "csltl"; break;
                        case BinOp::Gt:    opName = "csgtl"; break;
                        case BinOp::LtEq:  opName = "cslel"; break;
                        case BinOp::GtEq:  opName = "csgel"; break;
                        default: break;
                        }
                        std::string c = newTemp();
                        line(c + " =w " + opName + " " + a + ", " + b);
                        std::string ext = newTemp();
                        line(ext + " =l extsw " + c);
                        return ext;
                    }

                    case BinOp::Pow:
                        throw std::runtime_error(
                            "native: '**' not yet lowered");
                    case BinOp::In:
                    case BinOp::Is:
                        throw std::runtime_error(
                            std::string("native: operator '") +
                            binOpName(n->op) + "' not yet lowered");
                    default:
                        break;
                    }
                    throw std::runtime_error("native: unknown binary op");
                }

                case ExprKind::Call: {
                    auto* n = static_cast<const CallExpr*>(e);

                    if (n->callee->kind != ExprKind::NameRef)
                        throw std::runtime_error(
                            "native: only plain-name calls supported");

                    const auto* nm =
                        static_cast<const NameRefExpr*>(n->callee.get());

                    if (nm->name == "print") {
                        if (n->args.size() != 1)
                            throw std::runtime_error(
                                "native: print() requires exactly 1 argument");

                        std::string arg = emitExpr(n->args[0].value.get());
                        if (isBoolExpr(n->args[0].value.get()))
                            line("call $vayu_print_bool(l " + arg + ")");
                        else
                            line("call $vayu_print_int(l " + arg + ")");
                        return "0";
                    }

                    throw std::runtime_error(
                        "native: call to '" + nm->name + "' not supported");
                }

                case ExprKind::FloatLit:
                case ExprKind::StringLit:
                case ExprKind::CharLit:
                case ExprKind::ListLit:
                case ExprKind::MapLit:
                case ExprKind::Attr:
                case ExprKind::Index:
                case ExprKind::Lambda:
                case ExprKind::GenericType:
                    throw std::runtime_error(
                        "native: this expression is not yet lowered");
                }
                return "0";
            }

            std::string emitCond(const Expr* e) {
                std::string v = emitExpr(e);
                std::string t = newTemp();
                line(t + " =w cnel " + v + ", 0");
                return t;
            }

            void emitStmt(const Stmt* s) {
                if (!s) return;
                switch (s->kind) {
                case StmtKind::Expr: {
                    auto* n = static_cast<const ExprStmt*>(s);
                    (void)emitExpr(n->expr.get());
                    return;
                }

                case StmtKind::Assign: {
                    auto* n = static_cast<const AssignStmt*>(s);
                    if (n->target->kind != ExprKind::NameRef)
                        throw std::runtime_error(
                            "native: only simple-name assignment supported");
                    const auto* nm =
                        static_cast<const NameRefExpr*>(n->target.get());
                    std::string v = emitExpr(n->value.get());
                    std::string slot = lookupSlot(nm->name);
                    if (slot.empty())
                        throw std::runtime_error(
                            "native: variable '" + nm->name + "' not declared");
                    line("storel " + v + ", " + slot);
                    return;
                }

                case StmtKind::AnnotAssign: {
                    auto* n = static_cast<const AnnotAssignStmt*>(s);
                    std::string v = n->value
                        ? emitExpr(n->value.get())
                        : std::string("0");
                    std::string slot = lookupSlot(n->name);
                    if (slot.empty())
                        throw std::runtime_error(
                            "native: variable '" + n->name + "' not declared");
                    line("storel " + v + ", " + slot);
                    return;
                }

                case StmtKind::If: {
                    emitIf(static_cast<const IfStmt*>(s));
                    return;
                }
                case StmtKind::While: {
                    emitWhile(static_cast<const WhileStmt*>(s));
                    return;
                }

                case StmtKind::Pass:   return;
                case StmtKind::Struct:
                case StmtKind::Class:  return;

                case StmtKind::For:
                    throw std::runtime_error("native: 'for' arrives in a later phase");
                case StmtKind::Def:
                    throw std::runtime_error("native: 'def' arrives in a later phase");
                case StmtKind::Return:
                    throw std::runtime_error("native: 'return' arrives in a later phase");
                case StmtKind::Break:
                    throw std::runtime_error("native: 'break' arrives in a later phase");
                case StmtKind::Continue:
                    throw std::runtime_error("native: 'continue' arrives in a later phase");
                case StmtKind::Try:
                    throw std::runtime_error("native: 'try' arrives in a later phase");
                case StmtKind::Raise:
                    throw std::runtime_error("native: 'raise' arrives in a later phase");
                case StmtKind::Import:
                case StmtKind::FromImport:
                    throw std::runtime_error("native: modules arrive in a later phase");
                }
            }

            void emitBlock(const Block& b) {
                for (auto& s : b.stmts) emitStmt(s.get());
            }

            void emitIf(const IfStmt* n) {
                std::string cond = emitCond(n->cond.get());

                std::string lThen = newLabel("if_then_");
                std::string lElse = newLabel("if_else_");
                std::string lEnd = newLabel("if_end_");

                bool hasElse = n->elseBody.has_value() || !n->elifs.empty();

                if (hasElse)
                    line("jnz " + cond + ", " + lThen + ", " + lElse);
                else
                    line("jnz " + cond + ", " + lThen + ", " + lEnd);

                raw(lThen);
                emitBlock(n->thenBody);
                line("jmp " + lEnd);

                if (hasElse) {
                    raw(lElse);

                    for (size_t i = 0; i < n->elifs.size(); ++i) {
                        auto& ec = n->elifs[i];

                        std::string ecCond = emitCond(ec.cond.get());
                        std::string ecThen = newLabel("elif_then_");
                        std::string ecElse = newLabel("elif_else_");

                        bool lastElif = (i + 1 == n->elifs.size());
                        std::string elseTarget =
                            (lastElif && !n->elseBody) ? lEnd : ecElse;

                        line("jnz " + ecCond + ", " + ecThen + ", " + elseTarget);

                        raw(ecThen);
                        emitBlock(ec.body);
                        line("jmp " + lEnd);

                        if (elseTarget == lEnd) break;
                        raw(ecElse);
                    }

                    if (n->elseBody) {
                        emitBlock(*n->elseBody);
                        line("jmp " + lEnd);
                    }
                }

                raw(lEnd);
            }

            void emitWhile(const WhileStmt* n) {
                std::string lCond = newLabel("while_cond_");
                std::string lBody = newLabel("while_body_");
                std::string lEnd = newLabel("while_end_");

                line("jmp " + lCond);

                raw(lCond);
                std::string cond = emitCond(n->cond.get());
                line("jnz " + cond + ", " + lBody + ", " + lEnd);

                raw(lBody);
                emitBlock(n->body);
                line("jmp " + lCond);

                raw(lEnd);
            }
        };

    } // anonymous namespace

    // ===========================================================================
    // Runtime C source
    // ===========================================================================

    static const char* kRuntimeC = R"C(
#include <stdio.h>
#include <stdlib.h>

void vayu_print_int(long long v) {
    printf("%lld\n", v);
}

void vayu_print_bool(long long v) {
    printf("%s\n", v ? "true" : "false");
}

long long vayu_floordiv(long long a, long long b) {
    if (b == 0) { fprintf(stderr, "division by zero\n"); exit(1); }
    long long q = a / b;
    if ((a ^ b) < 0 && q * b != a) q--;
    return q;
}

long long vayu_mod(long long a, long long b) {
    if (b == 0) { fprintf(stderr, "modulo by zero\n"); exit(1); }
    long long r = a % b;
    if (r != 0 && ((r < 0) != (b < 0))) r += b;
    return r;
}

extern void vayu_main(void);

int main(void) {
    vayu_main();
    return 0;
}
)C";

    bool NativeCompiler::writeRuntimeC(const std::string& path) const {
        std::ofstream out(path, std::ios::binary);
        if (!out) return false;
        out << kRuntimeC;
        return true;
    }

    // ===========================================================================
    // Helpers
    // ===========================================================================

    namespace {

        // Delete a file quietly.
        void tryRemove(const std::string& p) {
            std::remove(p.c_str());
        }

        // Dump the first N lines of a file to stderr (used on failure to show
        // the offending assembly).
        void dumpFileHead(const std::string& path, int maxLines) {
            std::ifstream in(path);
            if (!in) return;
            std::string line;
            int n = 0;
            std::fprintf(stderr, "--- first %d lines of %s ---\n",
                maxLines, path.c_str());
            while (std::getline(in, line) && n < maxLines)
                std::fprintf(stderr, "%3d | %s\n", ++n, line.c_str());
        }

    } // anonymous namespace

    // ===========================================================================
    // Public entry points
    // ===========================================================================

    std::string NativeCompiler::buildQBE(const Block& program) {
        QbeEmitter e;
        return e.emit(program);
    }

    void NativeCompiler::dumpIR(const Block& program) {
        lastError_.clear();
        try {
            std::printf("%s\n", buildQBE(program).c_str());
        }
        catch (const std::exception& e) {
            lastError_ = e.what();
            std::fprintf(stderr, "native: %s\n", e.what());
        }
    }

    int NativeCompiler::compileAndRun(const Block& program) {
        lastError_.clear();

        // ---- 1. Emit QBE IL ----
        std::string il;
        try {
            il = buildQBE(program);
        }
        catch (const std::exception& e) {
            lastError_ = e.what();
            std::fprintf(stderr, "native: %s\n", e.what());
            return 1;
        }

        // ---- 2. Temp file paths (unique per process) ----
        std::string base = "_vayu_" + std::to_string(VAYU_GETPID());
        std::string ssaPath = base + ".ssa";
        std::string asmPath = base + ".s";
        std::string objPath = base + ".o";
        std::string rtPath = base + "_rt.c";
        std::string exePath = base + ".exe";

        // ---- 3. Write QBE IL ----
        {
            std::ofstream out(ssaPath, std::ios::binary);
            if (!out) {
                lastError_ = "cannot write " + ssaPath;
                std::fprintf(stderr, "native: %s\n", lastError_.c_str());
                return 1;
            }
            out << il;
        }

        // ---- 4. Write runtime C ----
        if (!writeRuntimeC(rtPath)) {
            lastError_ = "cannot write " + rtPath;
            std::fprintf(stderr, "native: %s\n", lastError_.c_str());
            tryRemove(ssaPath);
            return 1;
        }

        // ---- 5. Invoke qbe with the platform-appropriate ABI target ----
        {
            std::string cmd = qbePath_ + " -t " + qbeTarget_ +
                " -o \"" + asmPath + "\" \"" + ssaPath + "\"";
            int rc = std::system(cmd.c_str());
            if (rc != 0) {
                lastError_ = "qbe failed (exit " + std::to_string(rc) +
                    "). IL left at " + ssaPath;
                std::fprintf(stderr, "native: %s\n", lastError_.c_str());
                std::fprintf(stderr,
                    "  (if QBE rejected the target '%s', check `qbe -h` for the\n"
                    "   correct spelling, or set VAYU_QBE_TARGET accordingly)\n",
                    qbeTarget_.c_str());
                tryRemove(rtPath);
                return 1;
            }
        }

        // ---- 6. Preprocess QBE's assembly for the Windows PE assembler ----
        //
        // QBE always emits two things that are fine on ELF/Linux but that the
        // Windows-targeting GNU as rejects:
        //   1. No `.att_syntax` marker — as defaults to Intel on PE.
        //   2. `.section .note.GNU-stack,"",@progbits` — an ELF-only section.
        //
        // We strip the note section and force AT&T syntax.
        {
            std::ifstream in(asmPath, std::ios::binary);
            if (!in) {
                lastError_ = "cannot reopen QBE assembly at " + asmPath;
                std::fprintf(stderr, "native: %s\n", lastError_.c_str());
                tryRemove(ssaPath); tryRemove(rtPath);
                return 1;
            }

            std::string filtered;
            filtered.reserve(4096);
            std::string line;
            while (std::getline(in, line)) {
                // Drop ELF-specific sections the PE assembler doesn't know.
                if (line.find(".note.GNU-stack") != std::string::npos) continue;
                filtered += line;
                filtered += '\n';
            }
            in.close();

            std::ofstream out(asmPath, std::ios::binary);
            if (!out) {
                lastError_ = "cannot rewrite QBE assembly at " + asmPath;
                std::fprintf(stderr, "native: %s\n", lastError_.c_str());
                tryRemove(ssaPath); tryRemove(rtPath);
                return 1;
            }
            out << ".att_syntax prefix\n";
            out << filtered;
        }

        // ---- 7. Assemble to object ----
        {
            std::string cmd = ccPath_ + " -c -O2 \"" + asmPath +
                "\" -o \"" + objPath + "\"";
            int rc = std::system(cmd.c_str());
            if (rc != 0) {
                lastError_ = "assembler failed (exit " + std::to_string(rc) +
                    "). Assembly left at " + asmPath;
                std::fprintf(stderr, "native: %s\n", lastError_.c_str());
                dumpFileHead(asmPath, 40);
                tryRemove(ssaPath); tryRemove(rtPath);
                return 1;
            }
        }

        // ---- 8. Link object + runtime C into executable ----
        {
            std::string cmd = ccPath_ + " -O2 \"" + objPath + "\" \"" + rtPath +
                "\" -o \"" + exePath + "\"";
            int rc = std::system(cmd.c_str());
            if (rc != 0) {
                lastError_ = "linker failed (exit " + std::to_string(rc) + ")";
                std::fprintf(stderr, "native: %s\n", lastError_.c_str());
                tryRemove(ssaPath); tryRemove(asmPath);
                tryRemove(objPath); tryRemove(rtPath);
                return 1;
            }
        }

        // ---- 9. Run ----
        int runRc = 0;
        {
            std::string cmd = "\"" + exePath + "\"";
            runRc = std::system(cmd.c_str());
        }

        // ---- 10. Clean up everything (on both success and error) ----
        bool keep = (std::getenv("VAYU_KEEP_TEMP") != nullptr);
        if (!keep) {
            tryRemove(ssaPath);
            tryRemove(asmPath);
            tryRemove(objPath);
            tryRemove(rtPath);
            tryRemove(exePath);
        }

        if (runRc != 0) {
            lastError_ = "program exited with code " + std::to_string(runRc);
            return 1;
        }
        return 0;
    }

} // namespace vayu